apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: netipallocations.netinfra.darkbrains.com
spec:
  group: netinfra.darkbrains.com
  scope: Cluster
  names:
    plural: netipallocations
    singular: netipallocation
    kind: NetIPAllocation
    shortNames:
      - nia
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - reservedIPs
                - cloud
              properties:
                reservedIPs:
                  type: array
                  items:
                    type: string
                deploymentRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
                cloud:
                  type: object
                  properties:
                    provider:
                      type: string
                      enum:
                        - gcp
                        - aws
                        - azure
                    region:
                      type: string
                    zones:
                      type: array
                      items:
                        type: string
                strategy:
                  type: object
                  properties:
                    maxSurge:
                      type: integer
                      minimum: 0
                    maxUnavailable:
                      type: integer
                      minimum: 0
                reconcileInterval:
                  type: integer
                  minimum: 5
